[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "paydeck"
version = "1.0.1"
description = "Official Python SDK for PayDeck billing microservice"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
authors = [
    { name = "Vikas Budde (codecraker)", email = "vikas.budde@hotmail.com" }
]
keywords = ["paydeck", "billing", "razorpay", "stripe", "payments", "sdk"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

dependencies = []

[project.urls]
Homepage = "https://github.com/pisigmac/PayDeck"
Repository = "https://github.com/pisigmac/PayDeck.git"
Author = "https://github.com/codecraker"
